@startuml

actor User as user
participant Main as main
participant source_code_generator as coder
participant button_locator as yolo
participant UR3 as ur3
participant Camera as camera




user -> main: Source code request in english
main -> coder: request in english
coder -> main: source code as plain text

main -> yolo: Instantiate with:\n-pre-trained model\n-pre-measured w_real\n-pre-measured h_real
activate yolo

main -> ur3: Instantiate with:\n-pre-measured KRP\n-pre-measured camera_position
activate ur3

main -> camera: Instantiate with: ?TBD?
activate camera

main -> ur3: send it home
main -> user: asks to start UR3 script


'From now on, it is a loop
loop while there is letter in the soruce code
    main -> ur3: set command state to camera position
    ur3 -> main: signal when camera position reached

    main -> camera: asks for a picture
    camera -> main: send the current picture

    main -> yolo: send new picture
    yolo -> main: send current button positions in a dictionary

    main -> main: next letter

    main -> ur3: set command state to button push
    ur3 -> main: signal that button is pressed
end



@enduml